### ISSUE TITLE
Japan failing for final graph

### ISSUE THREAD

**Issue by ms3056** [greenwoodmark/covid19#2]
Hi - thank you for your work. I am learning quite a bit. 

I have tried to generate the graphs for Japan - they all work except for the last graph. The error trace is as follows:

```
IndexError: cannot do a non-empty take from an empty axes.

   for selected_country in country_list:
        analyse_country(selected_country, image_path)
        # TODO: understand why 'France'  new cases data very low - net of recoveries?

  l_bound, u_bound = np.percentile(
            proj_df.loc[mask, "error"].values, [5, 95], interpolation="linear"
        )
```

Any chance you could take a look?

**Comment by ms3056** [comment]
It seems the data for Japan is sensitive to the threshhold_data_deaths value - so I made the following code change (without fully understanding it) and the graphs for Japan proceed to be generated without error. 

```
        if selected_country == "Sweden" or selected_country == "Japan":
            threshold_daily_deaths = 20
        else:
            threshold_daily_deaths = 100
```

Thanks!

**Comment by greenwoodmark** [comment]
Thank you ms3056, yes that is the problem - need sufficient deaths for all elements of the model to fit properly. I will incorporate your change. Just let me know if you spot anything else.
